# Q2. Row Echelon Form:
Create a 5x5 matrix, A, with entries randomly chosen integers between 0 and 9. To generate the random matrix, set the random seed as the last two digits of your roll number. Reduce matrix A to its Row Echelon Form by performing elementary row operations.

In [1]:
import numpy as np

In [2]:
roll_number = 8  # Replace 8 with your actual last two digits
np.random.seed(roll_number)

In [3]:
A = np.random.randint(0, 10, size=(5, 5))
print("Original matrix A:")
print(A)

Original matrix A:
[[3 4 1 9 5]
 [8 3 8 0 5]
 [1 3 9 2 2]
 [6 8 9 3 4]
 [5 5 7 9 2]]


In [4]:
# Function to perform elementary row operations to reduce to row echelon form
def row_echelon_form(matrix):
    m, n = matrix.shape
    lead = 0
    for r in range(m):
        if lead >= n:
            break
        i = r
        while matrix[i, lead] == 0:
            i += 1
            if i == m:
                i = r
                lead += 1
                if n == lead:
                    break
        matrix[[r, i]] = matrix[[i, r]]
        lv = matrix[r, lead]
        matrix[r] = matrix[r] / lv
        for i in range(m):
            if i != r:
                lv = matrix[i, lead]
                matrix[i] -= lv * matrix[r]
        lead += 1
    return matrix

In [5]:
# Reduce matrix A to its row echelon form
A_row_echelon = row_echelon_form(A)
print("\nRow Echelon Form of matrix A:")
print(A_row_echelon)


Row Echelon Form of matrix A:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
